theme: jekyll-theme-hacker

# Name of your site (displayed in the header)
name: Chris Lee

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bitjjangi@gmail.com
  facebook: https://www.facebook.com/bitjjangi
  flickr:
  github: #daliworks
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: #daliworks
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: #channel/UCa7T7hj3F0x7brM6htUasyQ

markdown : kramdown
