# Site settings
title: Chris Blog
description: Chris Lee
keywords: chris, blog, camping, travel
author: Chris
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
