title: Chris Lee
email: bitjjangi@gmail.com
description: >-
  Hello, I am aiming at Software Engineer in Test.
  My job title is Web Programing, Project Manager, SQA Team Manger, W3C
  Contributor in Webapp part.
baseurl: ''
url: 'http://www.papajun.xyz'
twitter_username: bitjjangi
github_username: ''
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
