window.FOLDER_CONFIG = window.FOLDER_CONFIG || {};
window.FOLDER_CONFIG['03_travel'] = {
    "_folderName": "✈️ Travel Plan",
    "_order": [
        "japan_trip.html",
        "2026winter_island_compraison.html",
        "2026.jan.eastsouth_island.html",
        "busan_Ferry_trip.html",
        "christmas_korean_travel.html",
        "voyage_2026.html",
        "kyoto_family_trip.html",
        "yangyang_2025-christmas.html",
        "kyoto_plan_2026.html",
        "kyoto_travel.html",
        "north_kyoto.html",
        "north_kyoto2_html",
        "kyoto_subway.html",
        "kyoto_transit.html",
        "kyoto_malls.html",
        "kyoto_food.html"
    ],
    "japan_trip.html": "일본 겨울여행",
    "2026winter_island_compraison.html": "2026년 1월 동남아 가고싶은 섬 비교",
    "2026.jan.eastsouth_island.html": "2026년 1월 동남아 갈수있는 섬 비교",
    "busan_Ferry_trip.html": "부산발 일본 여행 선박 분석 & AI 플래너",
    "christmas_korean_travel.html": "크리스마스 한국 여행",
    "voyage_2026.html": "2026년 1월 여행 리포트",
    "kyoto_family_trip.html": "2026년 가족 여행 계획: 목적지 교토",
    "yangyang_2025-christmas.html": "양양·속초 크리스마스 가족 여행 계획",
    "kyoto_plan_2026.html": "2026년 교토 가족 여행 계획",
    "kyoto_travel.html": "교토 여행지 교통",
    "north_kyoto.html": "교토 북부 여행 계획",
    "north_kyoto2_html": "교토 북부 여행 전략 분석 리포트",
    "kyoto_subway.html": "교토 지하철",
    "kyoto_transit.html": "교토 교통",
    "kyoto_malls.html": "교토 쇼핑",
    "kyoto_food.html": "교토 맛집"
};
